export const blogData = [
  {
    id: 1,
    title: "Building Scalable APIs with Node.js and Express",
    excerpt:
      "Learn how to create robust, scalable APIs using Node.js and Express framework. We'll cover best practices, middleware implementation, and performance optimization techniques.",
    content: "Full article content would go here...",
    author: "Sarah Johnson",
    date: "2024-12-15",
    readTime: "8 min read",
    category: "Backend Development",
    tags: ["Node.js", "Express", "API", "JavaScript"],
    image: "/placeholder.svg?height=400&width=600",
    featured: true,
  },
  {
    id: 2,
    title: "React Performance Optimization: Advanced Techniques",
    excerpt:
      "Discover advanced React performance optimization techniques including memoization, code splitting, and virtual DOM optimization to build lightning-fast applications.",
    content: "Full article content would go here...",
    author: "Michael Chen",
    date: "2024-12-12",
    readTime: "12 min read",
    category: "Frontend Development",
    tags: ["React", "Performance", "Optimization", "JavaScript"],
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
  },
  {
    id: 3,
    title: "Database Design Patterns for Modern Applications",
    excerpt:
      "Explore essential database design patterns and best practices for building modern, scalable applications. From normalization to NoSQL strategies.",
    content: "Full article content would go here...",
    author: "David Rodriguez",
    date: "2024-12-10",
    readTime: "10 min read",
    category: "Database",
    tags: ["Database", "SQL", "NoSQL", "Design Patterns"],
    image: "/placeholder.svg?height=400&width=600",
    featured: true,
  },
  {
    id: 4,
    title: "Microservices Architecture: A Complete Guide",
    excerpt:
      "Understanding microservices architecture, its benefits, challenges, and implementation strategies. Learn when and how to break down monolithic applications.",
    content: "Full article content would go here...",
    author: "Emily Watson",
    date: "2024-12-08",
    readTime: "15 min read",
    category: "Architecture",
    tags: ["Microservices", "Architecture", "Scalability", "DevOps"],
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
  },
  {
    id: 5,
    title: "Securing Your APIs: Authentication and Authorization",
    excerpt:
      "Comprehensive guide to API security covering JWT tokens, OAuth 2.0, rate limiting, and other essential security measures for protecting your APIs.",
    content: "Full article content would go here...",
    author: "Alex Thompson",
    date: "2024-12-05",
    readTime: "11 min read",
    category: "Security",
    tags: ["Security", "Authentication", "JWT", "OAuth"],
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
  },
  {
    id: 6,
    title: "DevOps Best Practices for Startups",
    excerpt:
      "Essential DevOps practices every startup should implement. From CI/CD pipelines to infrastructure as code, learn how to scale efficiently.",
    content: "Full article content would go here...",
    author: "Lisa Park",
    date: "2024-12-03",
    readTime: "9 min read",
    category: "DevOps",
    tags: ["DevOps", "CI/CD", "Infrastructure", "Automation"],
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
  },
  {
    id: 7,
    title: "Machine Learning APIs: From Model to Production",
    excerpt:
      "Step-by-step guide to deploying machine learning models as APIs. Cover model serving, scaling, monitoring, and maintaining ML systems in production.",
    content: "Full article content would go here...",
    author: "Dr. James Wilson",
    date: "2024-12-01",
    readTime: "14 min read",
    category: "Machine Learning",
    tags: ["Machine Learning", "AI", "API", "Production"],
    image: "/placeholder.svg?height=400&width=600",
    featured: true,
  },
  {
    id: 8,
    title: "GraphQL vs REST: Choosing the Right API Architecture",
    excerpt:
      "In-depth comparison of GraphQL and REST APIs. Learn the pros and cons of each approach and how to choose the right one for your project.",
    content: "Full article content would go here...",
    author: "Rachel Green",
    date: "2024-11-28",
    readTime: "7 min read",
    category: "API Design",
    tags: ["GraphQL", "REST", "API", "Architecture"],
    image: "/placeholder.svg?height=400&width=600",
    featured: false,
  },
];

export const categories = [
  "All",
  "Backend Development",
  "Frontend Development",
  "Database",
  "Architecture",
  "Security",
  "DevOps",
  "Machine Learning",
  "API Design",
];
